name: ci
on:
  push:
    branches:
      - '!main'
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # 노드 설치
      - name: setting Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '17'

      - name: Cache
        uses: actions/cache@v3.0.2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      # cache 없을때(node_modules 변경될 떄)만 설치
      - name: install dependency
        if: steps.cache.output.cache-hit != true
        run: npm install

      - run: npm run test
        if: ${{ always() }}
